import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const source = await readFile(new URL('../ui/tracker.js', import.meta.url), 'utf8');
const { optimistic, acknowledge, validChange, duration, clockTime, localInput } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const ids = Array.from({length: 8}, (_, i) => `00000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`);
const base = 1780000000000;
const blank = {records: [], active: null, next: null, server_now: base};
const start = {action:'start', id:ids[0], operation_id:ids[1], start_ms:base, intensity:1};
const strength = {action:'strength', id:ids[0], operation_id:ids[2], version:1, intensity:3};
const finish = {action:'finish', id:ids[0], operation_id:ids[3], version:2, end_ms:base+65000, intensity:3};
assert.equal(validChange(start), true);
assert.equal(validChange(strength), true);
assert.equal(validChange(finish), true);
assert.equal(validChange({...finish, version:0}), false);
assert.equal(validChange({...start, intensity:4}), false);
assert.equal(validChange({...finish, end_ms:NaN}), false);
assert.equal(validChange({...finish, operation_id:'not-a-uuid'}), false);
const ended = optimistic(blank,[start,strength,finish]);
assert.equal(ended.active,null,'offline finish immediately freezes the timer');
assert.equal(ended.records[0].end_ms-ended.records[0].start_ms,65000);
assert.equal(ended.records[0].version,3,'queued operations use optimistic versions');
assert.equal(ended.records[0].intensity,3);
assert.deepEqual(optimistic(ended,[start,strength,finish]),ended,'DB snapshot containing queued events must not duplicate records');
assert.equal(blank.records.length,0,'optimistic rendering must not mutate authoritative snapshot');
assert.deepEqual(acknowledge([start,strength,finish],[strength.operation_id]),[start,finish],'only explicit receipts remove events');
assert.deepEqual(acknowledge([start],[]),[start],'no receipt preserves pending events');
assert.deepEqual(acknowledge([start],[ids[7]]),[start],'unrelated receipt preserves pending events');
const edit = {action:'edit',id:ids[0],operation_id:ids[4],version:3,start_ms:base-5000,end_ms:base+60000,intensity:2};
const changed = optimistic(ended,[edit]);
assert.equal(changed.records[0].version,4);
assert.equal(changed.records[0].start_ms,base-5000);
const remove = {action:'delete',id:ids[0],operation_id:ids[5],version:4};
assert.equal(optimistic(changed,[remove]).records.length,0);
const cloudOther = {...blank,active:{id:ids[6],start_ms:base+1000,end_ms:null,intensity:2,version:1}};
assert.equal(optimistic(cloudOther,[start]).active.id,ids[0],'conflicting local active remains recoverable until explicit discard');
assert.equal(optimistic(cloudOther,[]).active.id,ids[6]);
const second = {...ended.records[0],id:ids[6],start_ms:base+180000,end_ms:base+240000,version:1};
const history = optimistic({...blank,records:[ended.records[0],second]},[]);
assert.equal(history.records[0].previous_start,base);
assert.equal(history.records[0].previous_end,base+65000);
assert.equal(duration(65000),'1 分 5 秒');
assert.equal(duration(-1),'—');
assert.equal(clockTime(3605000),'60:05');
assert.equal(new Date(localInput(base)).getTime(),base,'datetime input round-trips in device local timezone');
console.log('27 queue and timing checks passed');
